src/App.js

Hey Tom,
I've cleaned up the code a little. It's **untested** as I'm not sure how to mimic your devops pipeline.
Let me know if there's anything I can do to build it - I'm more than happy to sit down for a bit and see if I've introduced any regressions.
Apologies in advance for the unintelligible diff 😛
Oliver

Clean up React code

---

.vscode/launch.json
src/App.css
src/App.js
src/index.css

* Fixes #7, fixes #8, fixes #12, and fixes #13
* Fix for #9 is merged upstream pending release
* Changed delete to affect all instances of an event, rather than 1 week

Fix several style and logic bugs

---

src/App.js

Fix deleting events after choosing

---

src/App.css
src/App.js

fix: correct days of events, shorten agenda

---

LICENSE.txt

Here is a list of contributors (including the new React code and the old Python scraper) who have made large contributions:
* @pl4nty 
* @BishopOfTurkey
* @OliverBalfour
Here is a list of other contributors to the Python scraper who have made very small changes:
* HarrisonOates
* Lutra-Fs
* mdchia
* samyex6
All the major contributors have consented to the CC BY-SA 4.0 license on Discord

Add CC BY-SA 4.0 license

---

package.json

chore: bump react-search-box version

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
src/Export.js
src/index.css

fix: export dropdown style and ICS download

---

src/Toolbar.js

fix: parse course search data client-side

---

.gitignore
src/App.js
src/Calendar.js
src/index.css

Added a button in the lower right corner that can be pressed to toggle a floating menu of (currently just one but can easily add more) buttons. Inside is a button that can be pressed to open a dialog menu that gives users an option to change the starting day of the week.

Added Floating action button with button to open a dialog for week starting date.

---

src/App.js
src/Export.js
src/Toolbar.js

Fix export links for Outlook.com and O365

---

.vscode/launch.json
api/GetICS/index.js

Fixes #51
Config change allows debugging Functions standalone, or when they crash

fix: remove unselected classes from ICS export

---

public/contributors.html
src/App.js

Added a contributor list that pulls a list of contributors from the GitHub public REST API. It's just a pure HTML page because I'm lazy and this will load faster than loading in the whole react library and won't slow down the existing page.

feat: GitHub contributor showcase

---

public/contributors.html

Apparently git history is "Cooked"

Removed contribution counts

---

.vscode/launch.json
src/App.js
src/utils.js

* Fixes part of #76
* Also adds debug task for Firefox - @angussidney hope this is useful :)

fix: various time/timezone compatibility issues

---

src/index.css

Should improve #64 - thoughts?

Constant height calendar rows

---

package-lock.json
package.json
public/index.html
src/App.js
src/Toolbar.js
src/index.css

No longer shall poor innocent uni students writing timetables in the dead hours of the morning be exposed to the horrors of a white background. 🌙☀️😎

feat: Add Dark Mode and Dark Mode Toggle Button

---

src/App.js

Added:
- Click-anywhere-to-exit functionality to week start day dialog
- mouse enter/leave mechanic for FAB menu

feat: new enter/exit flows for FAB menu and week start dialogue

---

src/App.js
src/utils.js

* Fixes crash when navigating from Facebook etc

fix: discard invalid querystring params or values

---

.github/workflows/build_and_deploy.yml
.github/workflows/pr_cleanup.yml
.github/workflows/scrape.yml
README.md

feat: run CI on PRs from forks

---

src/App.js

* Automatically create issues from Form responses
* [MS Form](https://forms.office.com/r/sZnsxtsh2F) stored in ANU tenant under CSSA Team
* MS Power Automate flow stored in my ANU account
* Closes #45

feat: report issues via a Microsoft Form

---

README.md

docs: add note regarding datasource

---

.github/workflows/scrape.yml
src/App.js

Addresses #191.
I can't test the Scrape workflow on the non-default branch, but it Works On My Machine™️ so the only reason it would fail is if `sed` isn't available in that image. I'll just keep an eye out for the next time it runs.

feat: add timestamp of last data scrape

---

api/package-lock.json
package-lock.json
package.json

https://github.com/Azure/static-web-apps/issues/1381

fix(deps): prevent @azure/static-web-apps-cli from updating to 1.1.7

---

src/index.scss

fix: remove current time indicator from print view

---

src/Export.js

Does anyone want to tell me why the Print button has a different behaviour to the Ctrl+P window????

fix: print styling regression

---

.github/workflows/build_and_deploy.yml

ci(build): allow manual triggering of external PRs

---

src/Calendar.js
src/utils.js

For example on main for comp1110 both workshops show reset

Fix reset being shown on workshops with only one option.
